version: '3.8'
services:
  portfolio:
    build: .
    container_name: portfolio-app
    ports:
      - "3000:3000"
    volumes:
      - vibecode:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
volumes:
  vibecode:
    external: true
